title: "Mutasem A. Razzek Portfolio"
description: "Aerospace & Mechanical Engineer | CFD | FEA | Private Pilot"

theme: jekyll-theme-chirpy
# OR for GitHub Pages with remote theme:
remote_theme: cotes2020/jekyll-theme-chirpy

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

baseurl: "" # leave blank unless in a subdirectory
url: "https://mutasemrazz.github.io/portfolio"

author:
  name: "Mutasem A. Razzek"

# Custom navigation links
nav:
  - title: "Home"
    url: /
  - title: "Aerospace & Mechanical Projects"
    url: /projects/aerospace
  - title: "Rocketry & SOAR"
    url: /projects/rocketry
  - title: "Oil & Gas Engineering Projects"
    url: /projects/oil-gas
  - title: "Aviation Experience"
    url: /projects/aviation
  - title: "Skills & Education"
    url: /skills
  - title: "Contact"
    url: /contact
