title: "Mutasem A. Razzek Portfolio"
description: "Aerospace & Mechanical Engineer | CFD | FEA | Private Pilot"

remote_theme: cotes2020/jekyll-theme-chirpy

baseurl: ""  # For GitHub Pages root
url: "https://mutasemrazz.github.io/portfolio"

author:
  name: "Mutasem A. Razzek"
  email: "mabdalrazzek@gmail.com"

plugins:
  - jekyll-remote-theme

