title: "Mutasem A. Razzek Portfolio"
description: "Aerospace & Mechanical Engineer | CFD | FEA | Private Pilot"
baseurl: ""  # Leave empty for GitHub Pages root
url: "https://mutasemrazz.github.io/portfolio"

author:
  name: "Mutasem A. Razzek"

theme: jekyll-theme-chirpy

plugins:
  - jekyll-theme-chirpy
