title: " "
description: "Aerospace & Mechanical Engineer | CFD | FEA | Private Pilot"
theme: jekyll-theme-minimal
url: "https://mutasemrazz.github.io/new-portfolio"
baseurl: ""  # Keep this empty if it's root-level

