title: "Mutasem A. Razzek Portfolio"
remote_theme: orderedlist/minimal
plugins:
  - jekyll-remote-theme

description: "Aerospace & Mechanical Engineer | CFD | FEA | Private Pilot"
baseurl: ""  # Leave empty for GitHub Pages root
url: "https://mutasemrazz.github.io/portfolio"

author:
  name: "Mutasem A. Razzek"